#!/usr/bin/env python3
"""Convert the Green Algorithms CSV data into a single JS file for the static site.

Reads sources/latest/*.csv (first row is metadata, second row is the header)
and writes site/data.js, which defines window.GA_DATA. No dependencies
beyond the Python standard library.

Usage: python3 scripts/build_data.py
"""

import csv
import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(REPO_ROOT, "sources", "latest")
OUT_PATH = os.path.join(REPO_ROOT, "site", "data.js")

APP_VERSION = "v2.2"


def read_csv(name):
    """Read a CSV, skipping the first (metadata) row, returning list of dicts."""
    with open(os.path.join(DATA_DIR, name), newline="", encoding="utf-8") as f:
        next(f)  # metadata row
        return list(csv.DictReader(f))


def to_float(value):
    value = (value or "").strip()
    return float(value) if value else None


def main():
    data = {"version": APP_VERSION}

    # TDP per core, by model
    data["cpu"] = {
        row["model"]: to_float(row["TDP_per_core"]) for row in read_csv("TDP_cpu.csv")
    }
    data["gpu"] = {
        row["model"]: to_float(row["TDP_per_core"]) for row in read_csv("TDP_gpu.csv")
    }

    # Carbon intensity by location code
    data["ci"] = {
        row["location"]: {
            "continent": row["continentName"],
            "country": row["countryName"],
            "region": row["regionName"],
            "ci": to_float(row["carbonIntensity"]),
        }
        for row in read_csv("CI_aggregated.csv")
    }

    # Cloud data centres (skip those with unknown carbon intensity location)
    data["datacenters"] = [
        {
            "provider": row["provider"],
            "name": row["Name"],
            "location": row["location"],
            "pue": to_float(row["PUE"]),
        }
        for row in read_csv("cloudProviders_datacenters.csv")
        if row["location"].strip()
    ]

    # Default PUE per provider (incl. "Unknown")
    data["pueDefaults"] = {
        row["provider"]: to_float(row["PUE"]) for row in read_csv("defaults_PUE.csv")
    }

    # Cloud provider display names
    data["providers"] = {
        row["provider"]: row["providerName"]
        for row in read_csv("providersNamesCodes.csv")
        if row["platformType"] == "cloudComputing"
    }

    # Reference values (memory power, car/flight/tree equivalents...)
    data["refValues"] = {
        row["variable"]: to_float(row["value"])
        for row in read_csv("referenceValues.csv")
    }

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/build_data.py -- do not edit by hand.\n")
        f.write("window.GA_DATA = ")
        json.dump(data, f, separators=(",", ":"), ensure_ascii=False)
        f.write(";\n")

    size_kb = os.path.getsize(OUT_PATH) / 1024
    print(f"Wrote {OUT_PATH} ({size_kb:.1f} kB)")


if __name__ == "__main__":
    main()
